import type { Metadata } from "next";
import Providers from '@/components/Providers'



export const metadata: Metadata = {
  title: "Growth Metrics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    {children}
    </>
  );
}
