import type { Metadata } from "next";
import "./globals.css";
import Providers from '@/components/Providers'
import { SidebarInset } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/shadcnkit/app-sidebar"

// Google Fonts fetching via next/font/google is removed to avoid
// network access during Docker builds. Using system fonts instead.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <AppSidebar variant="inset" />
          <SidebarInset>
            {children}
          </SidebarInset>
        </Providers>
      </body>
    </html>
  );
}
